spring:
  application:
    name: semantic-llm
  ai:
    ollama:
      base-url: ${LLM_URL:http://localhost:11434}
      chat:
        model: benedict/linkbricks-llama3.1-korean:8b

server:
  port: 8080