spring:
  application:
    name: semantic-llm
  ai:
    ollama:
      base-url: http://localhost:11434  # Ollama ?? ??
      chat:
        model: llama3                   # ??? Ollama ?? ??

server:
  port: 8080